### ISSUE TITLE
How stable is this repository?

### ISSUE THREAD

**Issue by epenet** [graham33/fiblary#9]
I opened this PR in the original repo: https://github.com/pbalogh77/fiblary/pull/3
I know see that you have already implemented it in your repo.

Have you considered making Home Assistant use your branch?
And have you considered what happens if like pbalogh77 you stop maintaining it?

**Comment by epenet** [comment]
I've just seen this: https://github.com/home-assistant/core/issues/66466 that you didn't follow-through on.

The main issue (as you have discovered) is making sure that if the repository owner goes away then ....

My suggestion would be that you ask  pbalogh77 to "share" the repository and allow access for other maintainers.
If that doesn't work, then you ask other maintainers to join you in case you go away.

**Comment by epenet** [comment]
Maybe start by pinging all members who have forked the project: https://github.com/graham33/fiblary/network/members

**Comment by rappenze** [comment]
@graham33 , @epenet: Is there any progress here? It looks like this library has a lot of problems in the V5 client version. I tried to switch it in HA but a lot of errors popped up. See https://github.com/home-assistant/core/issues/71399. As I'm a HC2 owner I cannot really support in correct implementation of the library for HC3. Any help here is highly apprecated.

**Comment by graham33** [comment]
@epenet @rappenze yes the pbalogh77 repo is definitely stale.  I've been trying to contact him for well over a year, so I don't think there's much chance of any solution involving him making any changes to the repo.

I think it probably still makes sense for HA to use this repo, as it least I'll be contactable and am happy to share access with other maintainers.  I didn't follow through on that yet since I wanted to have one last go at contacting @pbalogh77, but that obviously hasn't worked.  I'll make a PR.

@rappenze I'm also an HC2 user, so I don't think I can be a lot of help with testing.  I can try to help with reviews etc. but I don't have a huge amount of time to devote to this kind of thing unfortunately.

**Comment by spernesen** [comment]
If it's helpful, I have an HC3 and most of the device categories within the Z-wave network (such as lights, blinds, locks, thermostats, relays etc.)

Unfortunately I have limited programming skills, but can possibly help with extracting JSON from HC3, and possibly assist with testing in practice..

Just let me know. :)

**Comment by graham33** [comment]
> I think it probably still makes sense for HA to use this repo, as it least I'll be contactable and am happy to share access with other maintainers. I didn't follow through on that yet since I wanted to have one last go at contacting @pbalogh77, but that obviously hasn't worked. I'll make a PR.

https://github.com/home-assistant/core/pull/71542
